- name: ACS met Kubernetes
  href: ./index.yml
- name: Overzicht
  items:
    - name: Over Container Service
      href: container-service-intro-kubernetes.md
- name: Snelstartgidsen
  expanded: true
  items:
    - name: Kubernetes Linux
      href: container-service-kubernetes-walkthrough.md
- name: Zelfstudies
  items:
    - name: 1 - Containerinstallatiekopieën maken
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 - Een containerregister maken
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3 - Een Kubernetes-cluster maken
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 - Een toepassing uitvoeren
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 - De schaal van een toepassing aanpassen
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 - Een toepassing bijwerken
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 - Bewaken met OMS
      href: container-service-tutorial-kubernetes-monitor.md
- name: Voorbeelden
  items:
    - name: Azure CLI
      href: cli-samples.md
- name: Concepten
  items:
    - name: Beveiligde containers
      href: container-service-security.md
- name: Handleidingen
  items:
    - name: Kubernetes met Windows
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Web-interface van Kubernetes
      href: container-service-kubernetes-ui.md
    - name: Helm-grafieken implementeren
      href: container-service-kubernetes-helm.md
    - name: Jenkins en ACS Kubernetes
      href: container-service-kubernetes-jenkins.md
    - name: Concept gebruiken met ACR en ACS
      href: container-service-draft-up.md
    - name: Verbinding maken met een ACS-cluster
      href: container-service-connect.md
    - name: Een ACS-cluster schalen
      href: container-service-scale.md
    - name: Bewaken
      items:
        - name: Bewaken met Datadog
          href: container-service-kubernetes-datadog.md
        - name: Bewaken met Sysdig
          href: container-service-kubernetes-sysdig.md
        - name: Bewaken met CoScale
          href: container-service-kubernetes-coscale.md
    - name: Spring Boot-apps implementeren
      items:
        - name: Een Spring Boot-toepassing implementeren in Linux in Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Een Spring Boot-toepassing implementeren op een Kubernetes-cluster in Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
- name: Naslaginformatie
  items:
    - name: Azure CLI 2.0
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/compute/containerservices
- name: Resources
  items:
    - name: Azure-roadmap
      href: 'https://azure.microsoft.com/roadmap/'
    - name: Veelgestelde vragen
      href: container-service-faq.md
    - name: Sjablonen - ACS-engine
      href: 'https://github.com/Azure/acs-engine'
    - name: Prijzen
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Beschikbaarheid in regio’s
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Video's
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'